### ISSUE TITLE
Change units

### ISSUE THREAD

**Issue by yushangakki** [xamut/tmux-weather#1]
This plugin is amazing, but can I ask how to change the temperature units to metrix? thank you!

**Comment by ilya-manin** [comment]
Hey @yushangakki, thanks for using the plugin 😃 
Actually, there was no way to customize weather units, but I've just added it. So just add this line in your `.tmux.conf`:
```
set-option -g @tmux-weather-units" "m"
```

**Comment by yushangakki** [comment]
should it be  `set-option -g @tmux-weather-units "m"`? I downloaded the new script but it does not work. Should I change the url instead (I checked the wttr.in document) Thank you and have a happy thanksgiving!

**Comment by yushangakki** [comment]
My bad, I just found it worked now, maybe it just took a long time to change the display. Thank you! Happy Thanksgiving!

**Comment by ilya-manin** [comment]
Glad to hear it all worked out. Happy Thanksgiving too!
