### ISSUE TITLE
Unknown location; please try …

### ISSUE THREAD

**Issue by kierun** [xamut/tmux-weather#5]
Your plugin worked fine and suddenly I get a "Unknown location; please try" messages instead. It is odd since a `curl` provides me with the right answer. See screenshot. 

![screenshot](https://user-images.githubusercontent.com/3079575/83605796-71a85980-a570-11ea-9e57-ce656bceda87.png)

Now, my server could have updated something in the mean time but I could not see any evidence it had done anything that could have changed that. Of course, I might be wrong… 

Any idea?

**Comment by kierun** [comment]
Okay, some time later and I have the weather just fine. Odd… I am not sure how I can help debug that.

**Comment by Schievel1** [comment]
Just stumbled upon this. This happens when they are running out of queries. 
Try `curl wttr.in/YourCity` and it will give you a proper message back whats going on.

**Comment by thomaslagies** [comment]
I had the same issue, but it guess its from the default 15 minute wait time between the queries.
I set `set-option -g @tmux-weather-interval 1` and now my location displays correctly
change it back to 15, or remove the line once it is correct so you dont query wttr.in too often :)

**Comment by kierun** [comment]
Hum, this really should be closed…
